# Generated by Django 3.2 on 2022-03-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=8000)),
                ('vk', models.CharField(max_length=8000)),
                ('facebook', models.CharField(max_length=8000)),
                ('instagram', models.CharField(max_length=8000)),
                ('twitter', models.CharField(max_length=8000)),
                ('website', models.CharField(max_length=8000)),
                ('youtube', models.CharField(max_length=8000)),
                ('mainLink', models.CharField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.contacts')),
            ],
        ),
    ]
